import Head from 'next/head'
import * as S from '../styles/home.styles'
// import Button from '@mui/material/Button';
import { Header, Button, InputText } from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container>
        <Header>
          <S.ContentHeader>
            <S.ImgLogo src='./marvel-logo.png' alt='marvel' />
            <S.SearchHero>
              <InputText labelText='Nome'/>
              <Button label='Pesquisar' action={() => alert('Testando Botão')} />
            </S.SearchHero>
          </S.ContentHeader>
        </Header>
      </S.Container>
    </>
  )
}
